#!/bin/bash

set -eux

cd "${0%/*}"

# cargo build --release --features=composefs-backend

FROM="${FROM:-quay.io/fedora/fedora-bootc-base-uki:42}"
TAG="${TAG:-quay.io/fedora/fedora-bootc-uki:42}"

cp ../../target/release/bootc .

mount /dev/vdb3 tmp

# rm -rf tmp/sysroot
mkdir -p tmp/sysroot/composefs

IMAGE_ID="$(sed s/sha256:// iid)"
./bootc internals cfs --repo tmp/sysroot/composefs oci pull containers-storage:"${IMAGE_ID}"
COMPOSEFS_FSVERITY=$(./bootc internals cfs --repo tmp/sysroot/composefs oci compute-id --bootable "${IMAGE_ID}")

# See: https://wiki.archlinux.org/title/Unified_Extensible_Firmware_Interface/Secure_Boot
# Alternative to generate keys for testing: `sbctl create-keys`
if [[ ! -d "secureboot" ]]; then
    echo "Generating test Secure Boot keys"
    mkdir secureboot
    pushd secureboot > /dev/null
    uuidgen --random > GUID.txt
    openssl req -newkey rsa:4096 -nodes -keyout PK.key -new -x509 -sha256 -days 3650 -subj "/CN=Test Platform Key/" -out PK.crt
    openssl x509 -outform DER -in PK.crt -out PK.cer
    openssl req -newkey rsa:4096 -nodes -keyout KEK.key -new -x509 -sha256 -days 3650 -subj "/CN=Test Key Exchange Key/" -out KEK.crt
    openssl x509 -outform DER -in KEK.crt -out KEK.cer
    openssl req -newkey rsa:4096 -nodes -keyout db.key -new -x509 -sha256 -days 3650 -subj "/CN=Test Signature Database key/" -out db.crt
    openssl x509 -outform DER -in db.crt -out db.cer
    popd > /dev/null
fi

# For debugging, add --no-cache to podman command
sudo podman build \
    --from "${FROM}" \
    -t "${TAG}" \
    --build-arg=COMPOSEFS_FSVERITY="${COMPOSEFS_FSVERITY}" \
    -f Containerfile.stage2 \
    --secret=id=key,src=secureboot/db.key \
    --secret=id=cert,src=secureboot/db.crt

# rm -rf tmp/efi
# mkdir -p tmp/efi
# ./bootc internals cfs --repo tmp/sysroot/composefs oci pull containers-storage:"${IMAGE_ID}"
# ./bootc internals cfs --repo tmp/sysroot/composefs oci compute-id --bootable "${IMAGE_ID}"
# ./bootc internals cfs --repo tmp/sysroot/composefs oci prepare-boot "${IMAGE_ID}" --bootdir tmp/efi

umount tmp
